apiVersion: v1
data:
  config.yaml: |-
{{ .Values.pomeriumConfig | indent 4 }}
kind: ConfigMap
metadata:
  name: pomerium-config
  namespace: pomerium
  name: {{ include "pomerium.fullname" . }}-configmap
  labels:
    {{- include "pomerium.labels" . | nindent 4 }}

